# Generated by Django 4.2.28 on 2026-02-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookchapter_category_readingprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('chapter_page_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.bookchapter')),
            ],
            options={
                'ordering': ['book', 'number'],
            },
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_progress', to='core.bookpage'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['book', 'number'], name='core_bookpa_book_id_305660_idx'),
        ),
        migrations.AddIndex(
            model_name='bookpage',
            index=models.Index(fields=['chapter', 'chapter_page_index'], name='core_bookpa_chapter_ef731d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookpage',
            unique_together={('book', 'number')},
        ),
    ]
